drop extension if exists "pg_net";

drop policy "Anyone can submit to waitlist" on "public"."waitlist";

alter table "public"."waitlist" alter column "created_at" set default timezone('utc'::text, now());

alter table "public"."waitlist" alter column "id" drop default;

alter table "public"."waitlist" alter column "id" add generated by default as identity;

alter table "public"."waitlist" alter column "id" set data type bigint using "id"::bigint;

alter table "public"."waitlist" alter column "name" drop not null;

CREATE UNIQUE INDEX waitlist_email_key ON public.waitlist USING btree (email);

alter table "public"."waitlist" add constraint "waitlist_email_key" UNIQUE using index "waitlist_email_key";


  create policy "Enable insert for public"
  on "public"."waitlist"
  as permissive
  for insert
  to public
with check (true);



  create policy "Enable read for service role only"
  on "public"."waitlist"
  as permissive
  for select
  to public
using (false);



